server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location /api/account/ {
    proxy_pass http://account-service:8083/;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
  }

  location /api/orchestrator/ {
    proxy_pass http://transaction-orchestrator:8085/;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
  }

  location /api/ledger/ {
    proxy_pass http://ledger-service:8084/;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
  }

  location /api/ussd/ {
    proxy_pass http://ussd-gateway:8087/;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
  }

  location /lite/balance {
    proxy_pass http://ussd-gateway:8087/lite/balance;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
